# Generated by Django 3.1.7 on 2021-11-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210405_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profile'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Donor Profile', 'verbose_name_plural': 'Donor Profile'},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
