# Generated by Django 3.1.7 on 2021-12-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_of_heroes', '0003_auto_20211130_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
